services:
  backend:
    build: ./backend
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "5000:5000"

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "6969:80"

  automark:
    build: ./automark
    depends_on:
      - backend
    profiles:
      - debug
