services:
  backend:
    build: ./backend
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "5001:5001"

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "6969:80"

  test:
    build: ./test
    depends_on:
      - backend
    profiles:
      - debug
